version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
      time: "02:00"
    groups:
      actions:
        applies-to: version-updates
        patterns:
          - "*"
    cooldown:
      default-days: 3
    commit-message:
      prefix: actions
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    commit-message:
      prefix: flake inputs
    cooldown:
      default-days: 1
      exclude:
        - "*"
    groups:
      nix-updates:
        applies-to: version-updates
        patterns:
          - "*"
